### ISSUE TITLE
Example code has an error

### ISSUE THREAD

**Issue by vaithu** [vaadin/vcf-nav#14]
The example code is throwing error at this line

![image](https://user-images.githubusercontent.com/35440074/216741601-0d06058c-3898-4834-8b8a-f61154ad4be0.png)

Looks this is how it should be

```
 dashboard.getElement().appendChild(newItems.getElement());
```

**Comment by jouni** [comment]
Fixed in 29e2d50e28056ec171d094d668c768baf2cb39b1
