### ISSUE TITLE
Add feature flag for enabling Nav component

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/vcf-nav#21]

**Comment by bwajtr** [comment]
Yuriy said that we inspire in the Map component

**Comment by bwajtr** [comment]
Solved by [Experimental SideNav component Feature flag](https://github.com/vaadin/flow-components/issues/4981)

**Comment by ugur-vaadin** [comment]
Feature flags for both the web component and the Flow counterpart are included with the initial versions.
