### ISSUE TITLE
Should the Nav Items use RouterLinks in Flow?

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/vcf-nav#25]
The current implementation has regular anchors as part of the template of the nav-item element, but would it make sense to use RouterLinks provided by Flow?

Maybe that would automagically solve the following issues:

- https://github.com/vaadin/web-components/issues/5826
- https://github.com/vaadin/web-components/issues/5824
- https://github.com/vaadin/web-components/issues/5825

**Comment by ugur-vaadin** [comment]
Created a web component [issue](https://github.com/vaadin/web-components/issues/5819) based on this issue.
