### ISSUE TITLE
SideNav might not have appropriate semantics for expandability

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/vcf-nav#28]
A nav-item with sub-items is currently structured roughly as follows (omitting shadow dom boundaries and slots for simplicity):

- nav-item role="listitem"
   - anchor
      - text
      - button aria-label="Toggle child items" aria-controls="children" expanded="false"
   - role="list" id="children"
      - nav-item
      - nav-item
      - nav-item

(Note that the sub-list (with `id="children"`) is hidden, including from screen readers, until the parent item is expanded, so it's crucial for screen reader users to be able to discover the expandability.)

As the toggle button is inside the anchor, it is announced as part of the anchor's label, so a parent-item with the text _"Dashboard"_ is announced (at least by VO+Safari) as _"Dashboard toggle child items"_, rather than as something expandable or that has child-items.

Tabbing onward from the nav-item into the button inside it does announce the button as collapsed or expanded, but the association between the nav-item and the button is not particularly evident.

I'm not sure what structure would be more appropriate and provide better semantics and/or announcements. There are two vaguely similar examples in the ARIA Authoring Practices Guide:

- A) A [horizontal navigation](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation-hybrid/#mythical-page-content) whose parent items can be links themselves, in which the expand button is a _sibling_ to the parent's anchor rather than inside it;
- B) A much more complex [navigation tree-view pattern](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-navigation/), that uses roving tabindex and, although it uses list elements, overrides their semantics with `treeitem`s and `group`s.

Perhaps option B – the tree-view pattern – would be the best option, but it would also add a lot of complexity and require significant changes to the current implementation.

I suspect that, at the very least, we should move the toggle button outside of the anchor, and somehow ensure that it's announced in a way that clearly identifies the parent item that it's part of. That might be achieved by combining the parent item's text with a static sub-items text (configurable via i18n API) through `aria-labelledby` along these lines:

- nav-item role="listitem"
   - anchor id="anchor"
      - _link text_
   - button aria-labelledby="anchor subtext" aria-controls="children" expanded="false"
      - span hidden id="subtext"
         - _" sub-items"_ 
   - role="list" id="children"
      - nav-item
      - nav-item
      - nav-item

Hopefully this would lead the button of a "Dashboard" item to be annonunced as _"Dashboard sub-items"_.

**Comment by jouni** [comment]
Right, thanks for raising this issue. Now I feel stupid for something so obvious. Not sure why I thought it was okay to put the toggle button inside the anchor.

**Comment by ugur-vaadin** [comment]
Created a web component [issue](https://github.com/vaadin/web-components/issues/5814) based on this issue.
