### ISSUE TITLE
Implement ThemableMixin 

### ISSUE THREAD

**Issue by simasch** [vaadin/vcf-nav#3]
vcf-nav does not implement ThemableMixin so it's not possible to style the componentent.

It would be highly appreciated if ThemableMixin is implemented.

**Comment by jouni** [comment]
See the updated [README](https://github.com/vaadin/vcf-nav#styling) for quick instructions how to style this component.

Once this component is worked on as an official Vaadin component, it might be that we will end up using ThemableMixin for it as well, just to align with all the other components.

But as the importance ThemableMixin is gradually being downplayed, it might also we be that this component will be one of the first to not implement it, and rely on `::part()` styling.

**Comment by simasch** [comment]
I understand. But then make sure that everything can be styled. 
My issue was styling the background of the active anchor.

**Comment by jouni** [comment]
> But then make sure that everything can be styled.

Yes, already tried to do that. Please let us know if there’s something you are unable to style.

> My issue was styling the background of the active anchor.

Did you solve that already? Should be doable with

```css
vcf-nav-item[active]::part(item) {
  background-color: black;
}
```

**Comment by simasch** [comment]
Cool this works!

Thanks a lot
