### ISSUE TITLE
"" is not detected as active

### ISSUE THREAD

**Issue by simasch** [vaadin/vcf-nav#4]
I have a route:

    @Route(value = "", layout = AppMainLayout.class)

And add it like this to the nav:

     addNavItem(new AppNavItem(getTranslation("hello"), "", VaadinIcon.HANDSHAKE.create()));

Then this nav item never becomes active.

**Comment by juanmbellini** [comment]
Any news on this?

**Comment by juanmbellini** [comment]
However, if you set the Route with the "/" value, it also fails as it changes it into the empty string.

**Comment by jouni** [comment]
Yeah, I didn't mean to imply that you should have to change the route path to `"/"`. Rather that the nav component doesn't take this difference in the "root path" into account.

**Comment by simasch** [comment]
Are there any plans to fix this annyoing bug?

**Comment by jouni** [comment]
I meant to push this as a PR, but accidentally pushed to `main`. Here’s how I would fix this: https://github.com/vaadin/vcf-nav/commit/93e3e67f3710acbeea9a4658ebe0185bf36de0aa

**Comment by jouni** [comment]
@Artur-, should we publish a new version and test it in start.vaadin.com?

**Comment by Artur-** [comment]
Looks sane, go ahead

**Comment by simasch** [comment]
For me it works

**Comment by jouni** [comment]
Closing as fixed, then 👍
