### ISSUE TITLE
expand AppNavItem programmatically

### ISSUE THREAD

**Issue by dominik42** [vaadin/vcf-nav#8]
The AppNav/ AppNavItem should have the possibility to expand/ collapse it programmatically.
Therefore, please add the following method into the upcoming official AppNavItem.java (which is currently generated by the Vaadin App Starter at start.vaadin.com)
```java
public AppNavItem setExpanded(boolean value) {
    if (value) {
        getElement().setAttribute("expanded", "");
    } else {
        getElement().removeAttribute("expanded");
    }
    return this;
}
```

**Comment by jouni** [comment]
Yeah, makes perfect sense to add that. Thanks!
